[flavor]
use = "tokyo-night"
# For Yazi 0.4 and above
dark = "tokyo-night"


[icon]
prepend_dirs = [
	{ name = "Documentos", text = "" },
	{ name = "Imagens", text = "" },
	{ name = "Musicas", text = "" },
	{ name = "Playground", text = "󱊈" },
	{ name = "Projetos", text = "" },
]

